/**
 * One consistent screen policy per T2V scene.
 * Readable UI is never generated by the model.
 */

export const T2V_SCREEN_POLICIES = [
  "no_screen",
  "generic_unreadable_ui",
  "provided_asset_overlay",
] as const;
export type T2vScreenPolicy = (typeof T2V_SCREEN_POLICIES)[number];

export function parseT2vScreenPolicy(value: unknown): T2vScreenPolicy | null {
  if (typeof value !== "string") return null;
  const v = value.trim();
  return (T2V_SCREEN_POLICIES as readonly string[]).includes(v)
    ? (v as T2vScreenPolicy)
    : null;
}

export function screenPolicyConstraintLine(policy: T2vScreenPolicy): string {
  switch (policy) {
    case "no_screen":
      return "No phones, laptops, monitors, or on-screen UI in frame. No readable text.";
    case "generic_unreadable_ui":
      return "Generic unreadable UI chrome only; no legible or readable text, letters, numbers, or feed copy.";
    case "provided_asset_overlay":
      return "Use the provided overlay asset for any real UI; do not generate readable type.";
  }
}

export function promptRequestsLegibleScreen(prompt: string): boolean {
  const lower = prompt.toLowerCase();
  const withoutForbids = lower
    .replace(/no legible or readable text[^.]*/g, "")
    .replace(/generic unreadable ui chrome only[^.]*/g, "")
    .replace(/no readable on-screen text/g, "")
    .replace(/or readable on-screen text/g, "")
    .replace(/no readable text/g, "")
    .replace(
      /no phones, laptops, monitors, or on-screen ui in frame\.?/g,
      "",
    );
  if (/\bremains\s+legible\b/.test(withoutForbids)) return true;
  if (/\bclean,\s*legible\b/.test(withoutForbids)) return true;
  if (
    /(?:readable|legible)\s+(?:on[-\s]?screen\s+)?(?:text|type|letters|numbers|copy|ui|feed)/.test(
      withoutForbids,
    )
  ) {
    return true;
  }
  if (
    /(?:show|display|include|with)\s+(?:the\s+)?(?:clearly\s+)?(?:readable|legible)\s+(?:text|type|letters|numbers|feed)/.test(
      withoutForbids,
    )
  ) {
    return true;
  }
  return false;
}

export function screenPolicyConflictsWithPrompt(args: {
  policy: T2vScreenPolicy;
  prompt: string;
}): boolean {
  if (args.policy === "provided_asset_overlay") return false;
  return promptRequestsLegibleScreen(args.prompt);
}
